server:
  port: ${PORT:9293}
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/Tarefas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'